package advent.year_2023;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AdventOfCodeDay01Test {

    @Test
    void findLeftMostAndRightMostNumbers() {
        assertEquals(55413, AdventOfCodeDay01.findLeftMostAndRightMostNumbers(
                "51591twosix4dhsxvgghxq\n" +
                        "425nine\n" +
                        "llvmhjtr8nbbhrfone\n" +
                        "lpbjvpbtdfvtxtdvkpjs7qrvddkzmjtlqtg\n" +
                        "3sixnineseven\n" +
                        "rfmsqbkms7three\n" +
                        "33291six\n" +
                        "oneonevstpxxrjpnine7six\n" +
                        "75sevennine14mzqljsjfbb7two\n" +
                        "three6two9jckvk\n" +
                        "zprj8394threehczfkncntk\n" +
                        "mkqtlrzmzfsix2ccqsnnxtwo4sevenxp9\n" +
                        "tdszrfzspthree2ttzseven5seven\n" +
                        "two3fiveckrsjr\n" +
                        "four14three7\n" +
                        "4fdkcclmxmxsevenfiver\n" +
                        "5sjnnfivefourzxxfpfivenine7five\n" +
                        "77sixfive\n" +
                        "twofivecrkvmpcpvzddvzcmjhjlthree8fcrrninefive\n" +
                        "fivetwo562five\n" +
                        "2ninekvdbfnmjmd6ninentpktmgseven92\n" +
                        "2twonine\n" +
                        "5fivesprm4ndqzbqnjqx\n" +
                        "7jfq9\n" +
                        "1hgnkmx91\n" +
                        "2jcrmhfvntc3lqnine4five4\n" +
                        "zvqmpjrpninejhqrnineggghcrjfd3onefive\n" +
                        "11three64qjjhqdnonetwo\n" +
                        "rmvzjnbonetwo6\n" +
                        "eightfive698threenine9\n" +
                        "8eighttrfngsklrkfivefourninefourqhclfcp\n" +
                        "1z\n" +
                        "fivegfslvcvtvs4\n" +
                        "sfq1twosevendbjq2nine4rzmdpmgcx\n" +
                        "seven816one8jmcqqhfnthree\n" +
                        "twor4325rsl5\n" +
                        "four2vqhninexqqhlfhfouronejks1\n" +
                        "7hjmmxhdnine8\n" +
                        "1eight3hqgshtb147\n" +
                        "four6sixeightone\n" +
                        "twomvkjxbqxzhnnmjxstkgfhzzdsc1fivefivesix\n" +
                        "3slhhsfnkhhlxtvqfrhvdzzkvlzcnlxgd4ninechp\n" +
                        "meightseven8onegghfsfeight84\n" +
                        "kmxckzqdfeightsqfivefivetfg77\n" +
                        "dc8\n" +
                        "mktwonecvqsxhqrjfninethreethreedkllgfxrxrffzvdbqdj2c3\n" +
                        "8shsxjmqmb3kpvj485nd\n" +
                        "rbdlrxsmjvnkttnpfour6twoseven\n" +
                        "bkt1seven\n" +
                        "threehkjhm9\n" +
                        "threeeight8sevennine7nlx\n" +
                        "jmvj4ctqpccsixseven\n" +
                        "4fourmtwoxcsvlvlhctdpxns\n" +
                        "eight7three4729eightbslrgrhs\n" +
                        "26seven1\n" +
                        "7ffseven\n" +
                        "9rsgmlgcsevenxkmsd17three\n" +
                        "snzn6htcqxqj7bf\n" +
                        "ppr7six73znmtmgrzrp9\n" +
                        "61mj7dvddfseveneight\n" +
                        "threevfive3fourseven3\n" +
                        "xznsxcxsbggvctqqb82two\n" +
                        "five4none\n" +
                        "foursevenrl12threegpbvdsspkrfour\n" +
                        "9sevensixthreerftbxgthree\n" +
                        "6fph\n" +
                        "996three\n" +
                        "64pkndfphqrglbgcpseven\n" +
                        "72749twoeightcpqfzqcrns\n" +
                        "xnzzhvssixtrlfftrjr5two9threenine\n" +
                        "four8hzkkrpb71glpqsnkvcb\n" +
                        "sixsix1\n" +
                        "9lfdtwo4sevenjhv911\n" +
                        "chxjljdh8jztwo61three\n" +
                        "twothree11\n" +
                        "hft2dmntjgzg1\n" +
                        "rtfckbnqxfdldgttbltdr33kqhxhkeight4\n" +
                        "ninefourseven4nine5\n" +
                        "25fsmkbsevenpzhgdhnxnbsix3\n" +
                        "bd1frglljngg8one1\n" +
                        "34six\n" +
                        "96cpcmztffqdrfrfslfour4lpnbmrfm\n" +
                        "psxrlseven2zmkvrhckqcxdl91\n" +
                        "ninexkfjcjkjb8three4xeighttqsrgbmfdt\n" +
                        "2threesixeight1\n" +
                        "ggxzf3gkdvsqxggltxdhdbhm5\n" +
                        "sixtwo89six\n" +
                        "eightnine3\n" +
                        "threemdrhqpone6\n" +
                        "sncpmhtwozsfpcpxgq9three\n" +
                        "rtwone37three7xhzlckfclbltdkrgqbcrhpqzg\n" +
                        "68sixbgsz35\n" +
                        "kdeightwo69\n" +
                        "four7bfq3four\n" +
                        "sixone3fivedgmrrvjqrr7three7seven\n" +
                        "sixthree6\n" +
                        "onethree3onevdtlkrfour4\n" +
                        "eight4seven5cszgblfseven\n" +
                        "two8ddmjtg\n" +
                        "fivejnvrdmghnvrmrjeightnnxpv8\n" +
                        "2threezvklqkpml\n" +
                        "two76cdfrmfckbjc\n" +
                        "zqxpg42sixeightfour76\n" +
                        "3eightvqpxzsn2bnbkrfb49\n" +
                        "eight85five\n" +
                        "sixngs8xjseight4\n" +
                        "296pfsgnlpbmngzlrrldznmrj1mjgvtxkr\n" +
                        "six4bvrdgxh\n" +
                        "34eight56eightsixhphnbgscfb\n" +
                        "two4twosixthreeggfdzlbkxxqmtxtczdfj\n" +
                        "four4tqrjxxcrztwoeight\n" +
                        "one73zpfhjvjh2\n" +
                        "7eight35phcfcdzhhpzn49eight\n" +
                        "zqcmlcqfneightsixrpmmhcrssk6dclcpmhzqhrbcnkxjdfjvrf\n" +
                        "1threegkhpq7nfrksvm69nxpvgvthfzoneighttc\n" +
                        "gtjsevensixsixb9\n" +
                        "nine73nine\n" +
                        "cbhsddcmzmdv2bnnffour\n" +
                        "85hhqkqmv\n" +
                        "six2jfxfgpg9\n" +
                        "fiveeightskrn1\n" +
                        "khvcf3five8qj5\n" +
                        "sevenfive7ptb\n" +
                        "tscc9psz3gtnsnksn\n" +
                        "xzlh7zfivefivejgr\n" +
                        "one4nine8three3\n" +
                        "2kjkbbvftktkvpbp8gkcnrrkr6r\n" +
                        "565three718five\n" +
                        "twojjgcfz3fiveoneftvnldxdhr2\n" +
                        "13three\n" +
                        "phbvxsnnineksttklfljm85\n" +
                        "tvzpbgzhmbnine1eightbpjtkflllg\n" +
                        "7five3\n" +
                        "2623four\n" +
                        "nvfchhrbcone1nine\n" +
                        "mjv5vtmlmsfcfmt65five1\n" +
                        "7one2\n" +
                        "4six4\n" +
                        "dlbzctlxpjxxqk96pmdgdfblbfjnsxjmkoneqgeight\n" +
                        "seven4nzvxldvzvjpzlzxb4eightnine6\n" +
                        "2vzblzhrxnc8qtgvxxzgkeightblqfftjtnxrbpvlsgvd\n" +
                        "thfdzxfqcthqfcnrt2\n" +
                        "qxfpbbnfczfourh4twodjrhp\n" +
                        "4m2fivelklgfgr6three\n" +
                        "4tsbs74\n" +
                        "one6twomzfncms2lrgzgsspkjmcgqxp\n" +
                        "six5fourgzrhbvdnzzllh\n" +
                        "9seventwothree8sevenfive4two\n" +
                        "7eightdprzmjvsevenfourfiveeight\n" +
                        "twosjzhsb29lqzkjbtshp5\n" +
                        "8four6two\n" +
                        "bklkfctjb84one\n" +
                        "sevensevenfive7seven6\n" +
                        "vklhzsjz5fiveeight5\n" +
                        "fourmlthreecjspnchzrthree8tb\n" +
                        "7gsfvptnpcl2n82\n" +
                        "58mdllbtjkkzcmdgzbeightbzqmfour\n" +
                        "2vtlzkzlsfive92vbpnq\n" +
                        "jbcgqvr28ksbphtfourfourfksnxjhtb\n" +
                        "21ljfcmgtmdqfive\n" +
                        "threejhhstcxfive64sixeightthree\n" +
                        "7tqpqngnrmnnxt3pjbcqjmktvj\n" +
                        "fmqqc9twoone15four\n" +
                        "5six13dnkxtqrxrh\n" +
                        "8xxpnpfivethreeh5ktnpctlqrgtl\n" +
                        "9hgmlnzsbmbsbjbg9\n" +
                        "8mnlsqkpqp18jkftxzfcklsgkvjr4threergdbrrzbb\n" +
                        "eightglhhjsfl819lkzlxjvcshdtjhxvjs8\n" +
                        "gshmsmzfbcrhvnfnpppmmfmngcv2snrponeqgxvtx\n" +
                        "9sprkdkk3cpjzlzphfdbhczbpssix\n" +
                        "nine8954five\n" +
                        "oneonettsixckhgprszjckhx2\n" +
                        "seveneightgnhzhm9pkthree3three\n" +
                        "5mjkpk\n" +
                        "sevenfour832five\n" +
                        "fivellhglxm2twoneq\n" +
                        "fqtfqdgeight2lfklmhrnfive\n" +
                        "flqdfkmlfthdvzncvbfour7gq\n" +
                        "793\n" +
                        "fourninetwojrfp4three5three5\n" +
                        "snnnjlhcnine84eightjthbkgtslhp4skglpzhz\n" +
                        "mnxfgpg862ninefive26\n" +
                        "bmdtbfjonegprzlxqlkb4mcscbqnv\n" +
                        "nine9fourfourfive1fivethree2\n" +
                        "eightfqrqz8\n" +
                        "fourpkd1bpxczlzthreecptvjlgzfmtqnr\n" +
                        "25onejrksrlccgrqtkcsmzccnine\n" +
                        "5nine26three88\n" +
                        "25four299fourfour\n" +
                        "hlrbll8vnhjlfjrkd\n" +
                        "ffourthreefourkgjbsnbc6\n" +
                        "eight8mpqpsgxthreegmxrhqkqbhgstcz\n" +
                        "three82five1\n" +
                        "4dxvzg29fourdsh\n" +
                        "ffgdlggchpcq7four34lfive\n" +
                        "seveneight9eightnpjmh9eightfive\n" +
                        "bnjrnsdfjg6\n" +
                        "76five\n" +
                        "five4nine6six\n" +
                        "q339eightkhnjsixttvqzlbchleight\n" +
                        "koneightonenine2nftlzxnkbctmjvzk98\n" +
                        "511\n" +
                        "4cghqsix3bqr\n" +
                        "958three\n" +
                        "seven2vmrkjqgrlb5\n" +
                        "9three6one5jdrnlfour6nine\n" +
                        "four2xdrqqsktone\n" +
                        "1sevendxkhzglzxgcmonesixrplhlplhnone\n" +
                        "6threefourhshvnszlqrzb\n" +
                        "7hctfsqf2jzjkxbljg\n" +
                        "sevencxncnc68\n" +
                        "49lfdkv2zbhddmbfive\n" +
                        "sevenfdsmsmmgzv29two6rpxsgpdsjxljcthree\n" +
                        "hgfqhdfb4mninesevenzngfljcvpvvkmghqxoneseven\n" +
                        "gtlqcggrp6lzjfive3rtrqvszcrsevennine\n" +
                        "qvhztzsfddxbbxsr88\n" +
                        "nine5kfnninelknrbf5bjrrthv\n" +
                        "pfnmdzksjcjcbvlvgcbheight47\n" +
                        "sixfour8\n" +
                        "cdbxkcqseven1\n" +
                        "onefive65mdbrnlg\n" +
                        "vlcxxcxhfkjhm6two5\n" +
                        "bfpnhlzq3tgcmhd4\n" +
                        "6three69eightgmxsseven\n" +
                        "three1six\n" +
                        "fourgqqgvltwofkxzmcfdmz4\n" +
                        "24four68nxs84spjnpfsdv\n" +
                        "m1threesvlhmgsbn\n" +
                        "three7jcvclg84sixfjvvtkfk7\n" +
                        "hznlsixjqnlvpmninejrvfpplbm5\n" +
                        "mgfrn6\n" +
                        "xb9469\n" +
                        "48713fivefour6\n" +
                        "sevenfiverzlhdzr59lbtvltccgbstzxksb\n" +
                        "rxkppsh771\n" +
                        "dldhcgdvtwosix3\n" +
                        "one4phkrftwo\n" +
                        "rrdrpfddtphv88jldqht\n" +
                        "vgcpcmrj6\n" +
                        "9zdqnzlthreelxzmlhsgdc1pddz\n" +
                        "669onesix\n" +
                        "5eighthlbhzlpms7qvbftcrone\n" +
                        "8mttfjqjnsf528hzvljcx\n" +
                        "eight9tseven25csfeight1\n" +
                        "7threethreetcdxnhnnftwosevennine\n" +
                        "54tsrjthq831sixcmxzqg\n" +
                        "61eight9kb5\n" +
                        "qlxmg4zhcpfxvrhlgjlcbxvxsix\n" +
                        "95two\n" +
                        "four75eight\n" +
                        "6fbrnsflmxstwo\n" +
                        "25\n" +
                        "eightcdl979gxzv97eightwogdv\n" +
                        "eightgbx85sevenseven\n" +
                        "3rfvzeightsjcctzxvtcrsix\n" +
                        "fivevqgm14\n" +
                        "dbfkfnfbckncvseven83drnkzt1\n" +
                        "11ninesevenxlxfr\n" +
                        "4ptvstqt7fivebznine\n" +
                        "5qmcnfour9\n" +
                        "four5mndpqsmxninethree56ctnlcpbtzmthree\n" +
                        "four2bqnbcbninemccbzhrfourbgrccrsznskjn\n" +
                        "rjdfqd24seveneightwom\n" +
                        "9ztmbftvvzlqlr4\n" +
                        "qprftkd3vkfhtwofour33five\n" +
                        "fourdtmjbtvvdxdhj5\n" +
                        "jpttch9\n" +
                        "9jkngffbxhg\n" +
                        "one79twoonesix\n" +
                        "2eight528nine2\n" +
                        "psncczvbeight3\n" +
                        "4seven7nlgrlzsqjsdb51\n" +
                        "five98lqc8\n" +
                        "nine377rcgvvhdghrg5scmff1\n" +
                        "8fvcxpr6kx5cpcrjdpnjcsj\n" +
                        "ltlbphmcc7six2\n" +
                        "4threek\n" +
                        "8hzmfhrnvt\n" +
                        "tbmzgpgkkxc89z4sqpd\n" +
                        "fivefourdjpdgfournine37eightzqbpgcnfrq\n" +
                        "sqh6llxn9z\n" +
                        "five1sixrqqclkhx334sixone\n" +
                        "289\n" +
                        "nqcspsixone822five\n" +
                        "bq19\n" +
                        "mxdqptgg99982vpthreesgdgsf\n" +
                        "vp334fourhdtjvlgtwo9seven\n" +
                        "3five157sixgzgxxfive2\n" +
                        "dvmtwone3sixfivetwo6ninezpjv\n" +
                        "9trtrdkldqj429hsrtd8\n" +
                        "6three3sxsbbhpgsix1\n" +
                        "3gccsixcghh\n" +
                        "six4nnbg\n" +
                        "ppvljnh5\n" +
                        "sevenmghppptnrtrzh7\n" +
                        "4sevenszkgbpldhklrtclm\n" +
                        "9qjsxmrmdm\n" +
                        "twoskbhlqhnkmgzkpvtft9five2qrkeight\n" +
                        "1v\n" +
                        "988fkxgkbonerglfsknxr5eight6\n" +
                        "xkdklvjbhv977lvlnmrj3gnfjrnttm\n" +
                        "1fourthreesevensevenxfdmtdone\n" +
                        "fourmg4xtvjbfmqkhtbslq1onehmtrtvsslrjdfncr\n" +
                        "twosgdlxsixfive1\n" +
                        "bscpkcfp8mhpvzn7threefqgcpfpmftsrmktwo\n" +
                        "sixeight4vthcxd48two\n" +
                        "1ninehclngfzbktvpjone\n" +
                        "one2sixmzxdqxvg4oneoneztbmplctc\n" +
                        "5tkhrmfrvonetwo\n" +
                        "lfgveightnqdmrv9six\n" +
                        "zzgmcr1jgzjjljhqmtnbrnbt\n" +
                        "one3vfour7eight\n" +
                        "fourseven3ninenine5four\n" +
                        "92kpdtggsb\n" +
                        "onecsfdhsn3gqmtfhc\n" +
                        "bhflvgdfkhprqqdgs6one\n" +
                        "1five93pmrhdvmgp7onesix\n" +
                        "56mgkt\n" +
                        "rksixfourfourthreefive3fdrbtgmdt2\n" +
                        "8one7\n" +
                        "rgvccbsrphxkmdgjkrjjztdzzmkgqbcdkseven69\n" +
                        "three4eightsixjgbnthfxvltwosevenxjkd\n" +
                        "5cffmxhdbtgtlffdb\n" +
                        "8fivetwoneb\n" +
                        "5trtgsgkvplfvqccknine\n" +
                        "two4gjjmptwo\n" +
                        "two845lltssr6\n" +
                        "six8xngnhbctl\n" +
                        "nhbxglqfjrhmhneightqmvlnqtwo53\n" +
                        "7nsr\n" +
                        "one2seven\n" +
                        "8eight2jphsz9\n" +
                        "9fivebv7kmxqtdvxq\n" +
                        "ninec4four\n" +
                        "vrtczjzbzg8bgf\n" +
                        "pvhnfhvsixbppv4oneshhqp8jprm\n" +
                        "tnxqmfive1khnmb\n" +
                        "onefivechd69nine8\n" +
                        "sxeightwoeightkpjxbkrvtbllbxfshseven4threemkbx7\n" +
                        "twofgcfp7ddjqvhrbvmkjdsltfps9bttz6\n" +
                        "sixninezpsbrvhvlz4\n" +
                        "four6sbtdldjcjrn7\n" +
                        "79drd742\n" +
                        "mmccvnldbhxcfnpxrftqc1sixlncsqs\n" +
                        "jjdpbsm2\n" +
                        "9fnhthreefourtftrmqhkmxrpnnhbxvk\n" +
                        "five168sixs4\n" +
                        "65fourkpzbhhgsghxvhlvlftfmck62\n" +
                        "8fivesixsvmzjhdmdqsixntzrckdk\n" +
                        "gfzjxptdqnineonepqqsldlvjrg5pdgthrslpfcfive\n" +
                        "38mmkcseven2four\n" +
                        "vghjzfchxsqq8fivefourone1\n" +
                        "tttjzcm3\n" +
                        "jpn764tsmrfvtjp7four\n" +
                        "onelhbhkmf7\n" +
                        "5ssfzvfrrvgleight71\n" +
                        "52lkxkxdjch5\n" +
                        "3eighttffhffht4\n" +
                        "832\n" +
                        "2gbhzrgchz\n" +
                        "threessdmstrhchfq73ftcfbrtrvf\n" +
                        "8xqs9scc\n" +
                        "xglmdxq24two28kcckrsqpzone\n" +
                        "16mkcl\n" +
                        "ldhmz3\n" +
                        "xzvttst5\n" +
                        "drkkc3\n" +
                        "8zhbplhvcr4\n" +
                        "one1xzbrkd59\n" +
                        "xzzbsnktjhjltsfrrrz3four\n" +
                        "8vlfgxgzsnfljbnnmlpz5nine3three\n" +
                        "99onehzdqm\n" +
                        "5zdtrvccn\n" +
                        "75sixsixkxldjnxslnvggnvvjbzcrqveight\n" +
                        "9sixztkk\n" +
                        "three9sevenone\n" +
                        "zxsgxfxpkpp45\n" +
                        "9hkshgthreekkvrplztccvb\n" +
                        "sixbvdxrhrc16\n" +
                        "1jbjbqhnqgg5shmgfm9seven99fvpnrrpks\n" +
                        "sixstsxgbmcx12qhhdr\n" +
                        "9trfxqzkdstwo2dzone5three\n" +
                        "one3drbrbtsevenonekmfdlffive\n" +
                        "nsnchfkxttwo2zgpbvkvktwofour\n" +
                        "cnzgzdvfm9\n" +
                        "8fst5jsgmxhbgklninebkkrs577\n" +
                        "xskvpkzcx2twoninebslrbdmqseven\n" +
                        "qlbpjqmptkseven9lqmcdvjcxqsix4\n" +
                        "eight7six2\n" +
                        "33h8rxmtlctrz67dz\n" +
                        "3rmkrn83seven4bxthree\n" +
                        "mmznine55\n" +
                        "1onefour\n" +
                        "two4fivenine\n" +
                        "fivesevenpp2onexcxjvllseight\n" +
                        "onehtfzdtjxskmzsbc4sixfourz\n" +
                        "mfkttfxqvtdqdrl93\n" +
                        "567\n" +
                        "qqpnrfninetwo55eight\n" +
                        "4qqmlrfbfrvpxvphjpbc\n" +
                        "nltblqfourbxxrrgvgkcbb5hzzgfour5dmdxl\n" +
                        "three2526ngfzssixsixseven\n" +
                        "1tffj2fcddnfxrzx34\n" +
                        "59jd\n" +
                        "sevenr8sevenvxltmxcssttwo9\n" +
                        "svklhbtwoxbbmk6ninekptrln7sixjqbjgxdhzr\n" +
                        "krbmcxpnxfrn4\n" +
                        "pnkfournjgpggxzjd97two\n" +
                        "cplfrzbgbleight2z7six\n" +
                        "ninep8xxxnine\n" +
                        "xqlrnzlz92ninehblgkztwonerc\n" +
                        "1nine7\n" +
                        "one8three361two98\n" +
                        "nine367qqslvgcxftwo\n" +
                        "3fournine3twofkcdmx6\n" +
                        "1b2ninethree\n" +
                        "6one4sevencnlsqzzmcxkxfnqjone9csmkx\n" +
                        "oneeightgh44eight66\n" +
                        "6x527threethreerggpfcfqlf\n" +
                        "eight1tnine7gjvtpvmqb1seven6\n" +
                        "six45six7fourmnhbskfthree4\n" +
                        "ltf4\n" +
                        "3hgqgdsmnsnine\n" +
                        "hjqneight5threeeight\n" +
                        "onekxbrlhkxgxbmbn6eightfourltspzkqdnone\n" +
                        "llfphldmghqrcnineeightonefive9vldfskjbhl1\n" +
                        "sixpjf5gjkdqkvvqhj\n" +
                        "2five685kvh17four\n" +
                        "pgslffcdvsix7oneightcs\n" +
                        "lznbhzonefivezgj45crzfl\n" +
                        "twosjggnvbxcmtwo8four5\n" +
                        "fourhtstxbkcz6fclrvgfrgbv\n" +
                        "nine4ninefourfdkdmjvlvzgsnjsfseven\n" +
                        "three318lmzcfive57\n" +
                        "5pmcnc\n" +
                        "861\n" +
                        "qbbhpjsg5r2\n" +
                        "jtxcphmrjnscfhqhk6seven2threefive\n" +
                        "qd1sixninefour\n" +
                        "four7fivethree65\n" +
                        "7dlzrddgrgfour3hxsttlnkbm29\n" +
                        "four4twonine8\n" +
                        "5zblkgmxninesevenbrhntxm\n" +
                        "xfvl9589\n" +
                        "five2seventhree6gbzb2\n" +
                        "cvmqqtskxlthree1\n" +
                        "sevenseventwo9xthreevzfdmfqvdf6\n" +
                        "six72sixeightnine9\n" +
                        "xrjnqqtlxz8bbgsqrseven6two9\n" +
                        "29seven153eightzl7\n" +
                        "sevengntsfmzkfb8\n" +
                        "1fiveseveneightdbvbtszptqlnineseventhree\n" +
                        "four6rks1v\n" +
                        "52eightninez\n" +
                        "5jspztgxrpt\n" +
                        "bq8jpttmm2\n" +
                        "fourctnlpkbrsfive9qd\n" +
                        "85twothreebbpsjcfh12oneeightwov\n" +
                        "xhxgfrcljq7six\n" +
                        "zh9\n" +
                        "9sixfiveseveneight\n" +
                        "rgqzbrldqrhtzjbsbzggktnc4nine8one1\n" +
                        "xcmfbrprxr72qqtnine\n" +
                        "tjphvghjfthree1one\n" +
                        "twosixeight9fourone\n" +
                        "eight48xronebc\n" +
                        "t6two34nkmfgmsnnvlbq3\n" +
                        "eighteightkx86\n" +
                        "82b6fcvvxpsx84\n" +
                        "threeeight66two\n" +
                        "six4pkbhtxlteighteightsix\n" +
                        "three7snrrdfb8sixninetwo4mltj\n" +
                        "5jqbgnqthreemjzgbvpdeighteight8tvf\n" +
                        "nine6zrbpsfrfqnsixlkmxrkxln\n" +
                        "2fivedvkt2998\n" +
                        "j2eightzqspbs\n" +
                        "mmp694eighteight\n" +
                        "3chzvrsrhzrcrtwoone2\n" +
                        "qqqzxcqmbb8nine\n" +
                        "sixsone7onesix1vvrqszvmnrh\n" +
                        "8threegtfnmkgthreesixthreeglhzqq\n" +
                        "threefiveone2three6seven4\n" +
                        "sixzkqbcg1\n" +
                        "two7seven85five\n" +
                        "cfhg3zmpfd644\n" +
                        "btsrthdbkt6242dhl\n" +
                        "hqlgnine5two\n" +
                        "2zgftzs8twovt\n" +
                        "mmpcgngmjjvbnsix35threezxjjxsqnlv\n" +
                        "lmmqsevenvjcvcqj55fiveninernmn9\n" +
                        "two7rgsbxnmddtjd\n" +
                        "36foursixsevencjffhxrsq\n" +
                        "4jxzfhxrphtgbjqfivefive\n" +
                        "99pqtnvtwo9crsbvsnrmtpltthree\n" +
                        "threedhk3hgvkp8nvbk6\n" +
                        "fivelkxdgvsq6twofive9hzjkdz\n" +
                        "ps7two9pqnnnvqpdbcpttjgrjl\n" +
                        "jjcfkvqdcl4twothreetwosix\n" +
                        "47one525\n" +
                        "23three2\n" +
                        "eight9four7gddxxfxcm9gdmmnfvbxr1\n" +
                        "745\n" +
                        "gkblgnrzsblklpb5bc8ftrnineoneseven\n" +
                        "jghbzdlmqbjm5glsqfffvzksc\n" +
                        "eightsix1five\n" +
                        "nznrzbdsv4\n" +
                        "16vdxm2hlrgtvgtdrbsix\n" +
                        "txk26eightnrjxrrlvffour2\n" +
                        "threesevenddmrsghzsjk2bdcqx\n" +
                        "eightthree9blrfjvrpfnjcfqrxcnine1\n" +
                        "two7three81htcdvdnxg\n" +
                        "seven1three6\n" +
                        "kplnzdjmkcrthreefour38\n" +
                        "bvf1sevenmcdfnv9lpnnh\n" +
                        "6eightqcznninesix\n" +
                        "two3sevensnpf6v\n" +
                        "eightthreeeight4986\n" +
                        "9seven7nine6nineseven6\n" +
                        "3two91\n" +
                        "six97three26hlxczxp\n" +
                        "65twopggttdksmtsblfpjbcphzc8eightwopx\n" +
                        "mbxtfmkfourrkspbkvbrnljsjhzpqsgtvrr2\n" +
                        "sixseven9one5\n" +
                        "three7twob98\n" +
                        "6c\n" +
                        "5797xjtwo83\n" +
                        "chrbcms6vpmrpctssbvqmvreight76\n" +
                        "mthgpstgchone6two\n" +
                        "597\n" +
                        "1799gjjdgzhg9eight\n" +
                        "vzqkgj27zpvxltzvrfcl47\n" +
                        "381lmxkxrfhbxqeight89tdhpbpqnx\n" +
                        "sevennine4\n" +
                        "29ninetwo1tvhpr6three\n" +
                        "dlbqfsdmdxhszmcpzshdthree3hvc2csbtfthree\n" +
                        "19khmsnhone\n" +
                        "twofourbtlsl1\n" +
                        "3sevenssevenfivefour\n" +
                        "8seventhreesevenseven\n" +
                        "three27rseven\n" +
                        "1jbdtfcdvvbzhgfsixrzqxkfktjmhkhfive5\n" +
                        "onetnznrrcthreefmmfivesbsvg4twothreetwoneqq\n" +
                        "sbjfxeight2tzbdkvqmmdd2\n" +
                        "vc4xfsjmt\n" +
                        "bfive9dmqgfnzvtngkbvthlrfjmsjtclbzbszfour\n" +
                        "31nbzfqvckd\n" +
                        "26kcdkzbjnpkpljxhgnhjgmtbrvkntjbqtwo\n" +
                        "3eightthree\n" +
                        "eighteight88\n" +
                        "five6bsix3rkchjzlfour94\n" +
                        "one9rrrbx3eightone\n" +
                        "6fourkxpdmt852eight\n" +
                        "8xhfbqqklnfive2one\n" +
                        "4ninetwoone6\n" +
                        "seven5seven\n" +
                        "1vzprkvk\n" +
                        "mczkrcdx7rzvgdd6ktcnktpfkpp\n" +
                        "sixnine988one\n" +
                        "68shx\n" +
                        "jqfoneight4sevensevenhmcrqjlzhnl6vcsqgmgnnxqhvchx8\n" +
                        "1fourgqbjvjhzdppdq\n" +
                        "lcxjghp2\n" +
                        "sevenone8nlh5\n" +
                        "nine94krdvjv5seven3\n" +
                        "ninenineseven8threentgtlzfnrfbhxxzn8jt\n" +
                        "nine37\n" +
                        "hbzztninexrrktrlktwohr1765\n" +
                        "5sixjdvfxdxslhthreethree\n" +
                        "2eighteight\n" +
                        "dfnbf65\n" +
                        "4onenineqjnlpninekgk\n" +
                        "oneoneeight974\n" +
                        "4nqqm83ninezkmbcblh\n" +
                        "7tpjhbeight1\n" +
                        "fiveninefdcnfourvdjcnsshnine3fivefive\n" +
                        "344\n" +
                        "crnqzpztstxvcgjdmkp6\n" +
                        "hgcvbscglp63tpfive\n" +
                        "seven5fivesixcbtblmlsixgvfbqttzonedld\n" +
                        "43threep\n" +
                        "zshzcplxth4nine2zcgsbzdlxtzbxggnine\n" +
                        "cqtwoneone9ckhnzmzfsevenfour8j3\n" +
                        "fiveshs8ttpcsznh\n" +
                        "hdpqds3seventwokbzlhxpj\n" +
                        "joneight9\n" +
                        "hmxxnxhqfivefiveseventtgxqcxc3\n" +
                        "59sixoneonezjgbshzpfg\n" +
                        "1gqqz\n" +
                        "8two38fourjm7\n" +
                        "1fiveeight1four69\n" +
                        "88eightwoffg\n" +
                        "threenine3threegqvtvtxgninerdprd\n" +
                        "7sixthreesixsixmgzlqlbsslseven7\n" +
                        "threegmrbgmsfourfourbvmhzpctkd5rzx98\n" +
                        "five193146mmqmf\n" +
                        "41fourxone\n" +
                        "2jhgqrkmmgbthreeeighttxg\n" +
                        "5xxbgpmm3\n" +
                        "5twonineffsevenfivetwonine\n" +
                        "seven98\n" +
                        "one7532rcc\n" +
                        "8djrctpqvpcd\n" +
                        "eightqqnhfnn2pjsevensixx7nine\n" +
                        "jkzjrbhsevenseven1\n" +
                        "4tnkqxkl69nrktzz\n" +
                        "six88five9nplcm\n" +
                        "xngrktpqclsmkqggj935oneeight\n" +
                        "8fourgbns\n" +
                        "eight47nine1two147\n" +
                        "vpshrqvfkjctpmhcfc22eightmqdxlsngbfn\n" +
                        "rfive1kxfbcpq\n" +
                        "twompnqfvqxqninevgvhqlpfqc15seven5eight\n" +
                        "9fournine4ntvhbkbhqn48mqhqhltbjpzrrgb\n" +
                        "ninesix2four937\n" +
                        "6cxpmgqnchk33mfdxfqdhxbfiveonethree\n" +
                        "9mqmldz3kjnsgfoureight\n" +
                        "4dmxtdvqvrvdrbfour5q\n" +
                        "8eightmcsbfive11four2thqxmbktdl\n" +
                        "zddeightwosixlmhrzfksevensevenfive3seven7four\n" +
                        "lvgfftzceightsevensevennineseven5twobkd\n" +
                        "nine7three\n" +
                        "zlmfvjfrxrrdmtxg965msd4\n" +
                        "two9five4sevennmrvdgzrf1bjdzbtrdlb1\n" +
                        "tjbnzrpzrflpfsrprsg9\n" +
                        "fourzcqfonesix279\n" +
                        "75fxlvc\n" +
                        "ldvmnfqpll7fourqxzpfctfxp1nhrhpvkbtmone\n" +
                        "seven4ninebpbdfjsxxmbqvtwo6one8\n" +
                        "fivefive47seven\n" +
                        "rxeightwomgzhcbnlmj72\n" +
                        "eight34xhbcmeightfour3\n" +
                        "nxszsbltqhthree4\n" +
                        "7threefiveninecqzfdjpdcg\n" +
                        "kdfour2\n" +
                        "ktworhdsfhhfqcrbzdslthmt2\n" +
                        "dpjbqmd7689\n" +
                        "threesix8\n" +
                        "61113threenine\n" +
                        "ninenine77fhtvsmfh23onefour\n" +
                        "bccdxg5three\n" +
                        "2eight1bnrx\n" +
                        "eight7sixdvvrqgt46874\n" +
                        "35onekpnthreeprznkpfvlneightwom\n" +
                        "52five6\n" +
                        "one3foursjnngjznqkfqklhjn\n" +
                        "eighttwomzrxzfqgtdthree3scbjdnq\n" +
                        "9fivecjgdnkxrt\n" +
                        "5nine442fb8\n" +
                        "nine6one\n" +
                        "241fouronenrlb6\n" +
                        "97sstjznxfcpccngfl7cxmzzcvptfive\n" +
                        "gvtsxbqzcone52\n" +
                        "5845836fourfgrvrchv\n" +
                        "7247zxfkqhvd\n" +
                        "fourxtwonine2eightfive\n" +
                        "znjxhfour229three\n" +
                        "fiveone8qjfmjbnnc\n" +
                        "1sqdjlfiveh\n" +
                        "fivegxfj9pfbxf5\n" +
                        "cnxmvmcrm4cfivedcnrnneightwosd\n" +
                        "four3oneone\n" +
                        "hbtfjlnplcsrxkt6rcqpfdseveneightwoh\n" +
                        "jqknine9xfour43sevenbgznxhh\n" +
                        "pvtztgjv47\n" +
                        "one9oneeight\n" +
                        "3npsq\n" +
                        "ninekmzdninejk7\n" +
                        "6threeninefhcpbb\n" +
                        "266\n" +
                        "pvtwocthreeeight1\n" +
                        "lpmshscqztgsgsb2zfcddqnvkseven\n" +
                        "dmoneighteight78oneeight9zqszseven\n" +
                        "eight8eight\n" +
                        "fcdlflbtfiverxfx9\n" +
                        "five7six5\n" +
                        "hhvmsspr4four8hhcjdhnthree\n" +
                        "three8qfzjpdztwodrkg5cg\n" +
                        "919lhzrx1\n" +
                        "foursevenfourfive6lvfour57\n" +
                        "crzmt7\n" +
                        "two71pzxnxtjkngfzm\n" +
                        "sixbmzlvcnine9\n" +
                        "hfbeightwo3eightfoursixfive\n" +
                        "j5twotwo57nine\n" +
                        "rmqq3sbjqnqmdjhmbp91hp\n" +
                        "3threezr\n" +
                        "fivesixfour81jqxx\n" +
                        "2bfeight7nine7\n" +
                        "fourfiveqjfkzsdxmgjmpmtone3hbgcvq\n" +
                        "7nrshoneninetwocpphnrfprz2five\n" +
                        "twoseven1bqjgdz2\n" +
                        "one7qonevmvb4sixhsbqgp\n" +
                        "fivethreethreegmdh1\n" +
                        "lv7d89\n" +
                        "2tbrnmflxfhhsixddn\n" +
                        "6sevennlhxsevensixt\n" +
                        "pd2kkfvtjbbgvfrcts\n" +
                        "djfoursevenflp2three6\n" +
                        "bppkvmxcrvffssdxgrr6mtlthree9six\n" +
                        "4szvlsixsevenxttwo\n" +
                        "ppggtqx8\n" +
                        "two3three6five\n" +
                        "threegplsmsjzjfcctwo6tkrkzmnk\n" +
                        "srtj2tsnxthreeonethreep\n" +
                        "szhnzblxslqthreejveightfvrrhbcqjqmmvczh1\n" +
                        "five2five25\n" +
                        "btvlzjhrxxdqdmbbcrmbffpmlmr9four\n" +
                        "1jdrpjpvkmmseven\n" +
                        "85bbbht\n" +
                        "2onel2p\n" +
                        "hdsfftwotpqcgdbdjbgnvfone3eight\n" +
                        "fourdgtccrxdnvfszgkjsj38\n" +
                        "twonine6twotvqxpskhonejsnpmtpctjfive6\n" +
                        "29eightcgskgdnmnhkpp63seventwo\n" +
                        "2seventwofhktwo9\n" +
                        "8kx\n" +
                        "32zxdzvfzjvtwofive9sevenfive\n" +
                        "2seven8pmdnnthreehnvltl7\n" +
                        "33sevenfournvnjp24\n" +
                        "two3m9kcsppfour\n" +
                        "hjfb9six5gtbppmzlfmfourtwodqzppcldd2\n" +
                        "4qlkz3\n" +
                        "4ninejzgpnkvq\n" +
                        "fbcpkspbcgrn6dmclmnqldeight\n" +
                        "sixtwodphp833\n" +
                        "sevenonesix5eightsrzpjzpj45rczn\n" +
                        "9fiveltfqjmkzbrm8oneightbq\n" +
                        "mxfqsrs5fpeightfive7mvclrlqhhkptpbqq\n" +
                        "438rktthreegvhltmsv\n" +
                        "dcl9xnntwosixthreesix7\n" +
                        "csxhsvkkkhfour4slkvjk1eight89\n" +
                        "three2eightfiveone\n" +
                        "17kqnstzmbthree9seventpld35\n" +
                        "ztxjhftwo1f\n" +
                        "ccfvc3three9five\n" +
                        "fmngmbkjppkxjnzqbqldmspbrrrhhrkrsix4\n" +
                        "9fivejthreepjtmtfive455\n" +
                        "4ncdvqfiveonefive5zxgjpptbnbsmbrfdpqrjnx\n" +
                        "ljctvztrxncpxsdtttwo2tnkkt\n" +
                        "five544mlzkztsblt17fivesix\n" +
                        "9five35bkbpjc\n" +
                        "6fourtwo\n" +
                        "nine5hqlbjp1onenvvnvsseven\n" +
                        "5qbvsbxtktqhgqxfgprsgsrrpdtpcmr8\n" +
                        "hhsgjxlz3gzxhz14fourtwofq\n" +
                        "6three8rmtrbnhvr\n" +
                        "9bhxvmhldnm6\n" +
                        "vkjjpkgdmxrzzfour7\n" +
                        "rhvrsrthsevenfour3eight5one73\n" +
                        "msqdzmfzfeight6qhrvzcdxfourrleight84\n" +
                        "pjtfflgfhqnpdk6three63five9six\n" +
                        "1sixcpcvbnnine9eightonenlnjfdfdmxcmcb\n" +
                        "zpgrbsevenmqskhgtrm6\n" +
                        "8hnqmmgrnsxhrxjjc2qjbbvpknh82\n" +
                        "5six7threepx\n" +
                        "bmlxvnqrxtqzkdlnnine5two9bpphfdhqj\n" +
                        "mtxrblghxrsbxhmgnbvgvffivenine49ztktxvfvseven\n" +
                        "tnqclrllq9fivebddnv\n" +
                        "56seven222pkmqk\n" +
                        "74eight9pfqghssgk\n" +
                        "nhmzdpbnlreightqgljp6\n" +
                        "nf3three2\n" +
                        "eight9glknfltsqsfdsixfour2tcfnzfmf\n" +
                        "four1ninetwo4sckcbgzrx663\n" +
                        "eightbcfsevennqznfmfivetwo7qgdjtwo\n" +
                        "64three\n" +
                        "8vgggxllsrhqjh2\n" +
                        "7jhthmpmlxlptgbnscxcthreeeighttwo3seven\n" +
                        "ktqlfveight1eightjnfxvvjk\n" +
                        "99qjcxgnpdvnbjqprbqnsjone3ninenmxkslmdsx\n" +
                        "9gn2\n" +
                        "qtlztwo7eight2\n" +
                        "nvzhsjsdp4sgrbmx36\n" +
                        "fldvmnlkq52nqtsccgfgtwolm7mmb\n" +
                        "tzvgkfx6ssnxfeightwov\n" +
                        "rrl8pxjj6onefour\n" +
                        "3hzhqbrdspfrn2eight8\n" +
                        "jcrcxtqh8three4\n" +
                        "ttwone449cxvvljcpzpqmngtzslnq\n" +
                        "3gnkgbjnsmxv2fourd8\n" +
                        "9zt\n" +
                        "kckeightsix8oneeightsix36\n" +
                        "vjcg4p\n" +
                        "jkzr3\n" +
                        "twofiveone1four9seven5cnhzm\n" +
                        "6one6\n" +
                        "s2twosixfvgrglfive2mtkrxznllj1\n" +
                        "cnhbzthlzllgghkxjgtrph45\n" +
                        "six5two\n" +
                        "nine5threefournine\n" +
                        "1rkbvrk8threevfkdbvxgj\n" +
                        "28six7dvone8\n" +
                        "74seven\n" +
                        "6threeseven92rvpg1\n" +
                        "hxvthvgk8vhn6kmljfnl\n" +
                        "fourztpprfkonemnjbsfdjlj8\n" +
                        "djnhxfxxl1five2threezgthn7\n" +
                        "vmhmlgljrpsix93sssixsevensix\n" +
                        "dqk8nrsrk\n" +
                        "jjtdjkfivegpfspqqjthreedkntgjslqreight7n8\n" +
                        "8four12\n" +
                        "8vlcfsixthreelvvdv\n" +
                        "zsjqvmghp6seventwo\n" +
                        "6tnjfl2cfzcbgqp5\n" +
                        "vgjxleightzqfklqdx4vlpvp2gqxdxpzk4\n" +
                        "12mshtkbgsndrdx7three\n" +
                        "htckznt2threeninej4fhmrtthreeeight\n" +
                        "four8hdbrmptjnine\n" +
                        "2xbk\n" +
                        "ljgcscxxjgdbpdpzfcchrqnmqqthree8\n" +
                        "three7six51\n" +
                        "four5five92ftqhjhx\n" +
                        "eightfthreebzbhk4tceight\n" +
                        "2fivethreefiveeight9fbk\n" +
                        "9four613two8cnpzgcrnmc3\n" +
                        "fqfive38\n" +
                        "nine88mkthree99lkvzgvpjk7\n" +
                        "784dxxcpszbzkdlsrgnnqfsixone7twonemvh\n" +
                        "onetwo5tzggnsix2\n" +
                        "xsclx3twojhslqrnc32pxfqsjxctnb4\n" +
                        "zrdbcccznzlfgz8jfpgllczxtnpmp58one\n" +
                        "four21one925rntdr\n" +
                        "38six\n" +
                        "seven3nfttdgkjhklmdqbkv8threefour\n" +
                        "75kblsbqhonevsx\n" +
                        "fourztseven8twothtwo\n" +
                        "gmktvrd44twonine4pnbrkhhzpl8five\n" +
                        "nineslj1six8two\n" +
                        "one98mxnkrbv\n" +
                        "9zmfour\n" +
                        "8dkfmthstlqvs9r\n" +
                        "cjmcjjjvmceight9rslcctdslsxthreexsjbffnine\n" +
                        "5eight677\n" +
                        "4twothree\n" +
                        "cvqbrkmgthree4tbmzrhqtpx\n" +
                        "24twoone\n" +
                        "nphprsbcfhcfrggktgzgvrninesixdnchjd2\n" +
                        "9sevennmxzpjbhct\n" +
                        "sbchgzqgdk8twosix667\n" +
                        "hkjlpqgtmglv3eighttwo7two\n" +
                        "gflktjvlfivetbgmbsxzdpdxjdgkzvn851sixfour\n" +
                        "five2ffivefiveonekldfpcfjg\n" +
                        "mlnvqltfsixnxqxsgfpxrpsxmmlnzsnineeight5\n" +
                        "six1z\n" +
                        "sevenpvhgctkcvgtjstwoeightzgqlcgq1gxzj\n" +
                        "fivenine13rbbxfs1zpvrstlkceight\n" +
                        "6zmcggdqbfptwofourfphdbdg99four\n" +
                        "one65ninetljqcfive8\n" +
                        "six57fourthree4fzctnjzcdm\n" +
                        "181one\n" +
                        "3one315gftsbtnggrq\n" +
                        "gcdvnzbvv55onemgcftkmzrxf\n" +
                        "697cnzql8eightvdsngsglkfour\n" +
                        "fourfiveqjptdn6\n" +
                        "pq83six7fprdbzvmgrhkzmjmxgnkcr\n" +
                        "nineeightfivesix8\n" +
                        "fiveseven931xhtnvrtr9three\n" +
                        "seven9ninetkhldts\n" +
                        "6threehlzfbppqmhrtxnfoursix2cxn9\n" +
                        "mphgdnggjt3flmdz14ninejjskfivenine\n" +
                        "boneight7one19179\n" +
                        "npdjlhskrdmvsvhtldsthree5tpt\n" +
                        "6rvpnvdqqpkkfvgclctqcmpdfvftt68\n" +
                        "91four3twoones\n" +
                        "seven793\n" +
                        "8h2four6cdsevencsjvcgdlrj\n" +
                        "4bzxqvp74mmdvjfdvq4fivec\n" +
                        "31tlvlrb75\n" +
                        "nndfct5ninesix\n" +
                        "ncqsnf6six\n" +
                        "fiveonefour8\n" +
                        "sixtwo6zjhvhkoneeighttbfv\n" +
                        "three5dcpmcsnmfhtwo5\n" +
                        "eightnqqkpnine4ninegb\n" +
                        "lgnsrbbtkgtwo7eightthree\n" +
                        "rlpcrnscknpjpqm2qqpllrzk8p9\n" +
                        "tvpqncpmffpmv9nineninesixnjbhbhgdlf2\n" +
                        "lzrhjdkfhn1\n" +
                        "jgjfckbrpvc3fouronefourfive3eight\n" +
                        "twozhkpzcdkjfour8eight\n" +
                        "5sevenfourtwo4\n" +
                        "1sevenfivehvppxvxvcnsnhdrflonefour\n" +
                        "4pshnstwo46fivetwoone\n" +
                        "three1onemdlc8pcqkzsrnhqone\n" +
                        "qvgfvfxnrp5bqdrlqd\n" +
                        "jzgcnslrfxxc72bqqqrzltqm18four\n" +
                        "nmjlnxktmvzzrgkbrffourdddbbt7eight\n" +
                        "3two9twothreerlztqftcgkznfour\n" +
                        "8fivefive5tkv\n" +
                        "4vtsnlclbb37eight2xprhpnddzj9\n" +
                        "8hbmfjxmqckxqrdjqxrnhg\n" +
                        "onef6\n" +
                        "8fivezcjtworgbxrfkjkbk5mdkdgfbnkkkljlv\n" +
                        "5six6prgqhbvcrr1msjcct\n" +
                        "mvzdrmdlrsdz9nqmbkb6286\n" +
                        "367\n" +
                        "94vjktbt\n" +
                        "twofivefour7three454\n" +
                        "2n\n" +
                        "six224\n" +
                        "z841dzxcthdx\n" +
                        "fourvnlj7twocchdcn976four\n" +
                        "threexmxq5five\n" +
                        "dscbqrjqmssnzbbdtx34\n" +
                        "8sevenhrvzqskpczsfhzrhrfch\n" +
                        "4qx\n" +
                        "6eightnine\n" +
                        "cnbxjrbsseven8hbdfmjvk6sevendrglnfq3six\n" +
                        "82threengstmq\n" +
                        "19f\n" +
                        "cvjrhrnxnfiveksrjgh8\n" +
                        "2six1dlpdds\n" +
                        "5xzhhnqpnsix8qthckdhggfdfour7\n" +
                        "9threetwoqznvtb4\n" +
                        "one8dseven\n" +
                        "3fivefourjzbk4seven8tvqgvh\n" +
                        "9kffjzvfxtwofive3seventhree5\n" +
                        "5onerxdcrrlgvfbrvrphnine5eight\n" +
                        "614pnrbdp\n" +
                        "eightfour1cvxjbztxgzznlpr8qbzkz35\n" +
                        "four5seventwo3\n" +
                        "9fourzzjfdqdkmxbeight41eightwopr\n" +
                        "eight6rfdhz793twonevkf\n" +
                        "vmrkgjgthreethree8ninesevend6hmjmkfdqz\n" +
                        "vqstkklpj4j8\n" +
                        "72jglrpp57nine7vcr\n" +
                        "sevenfbbgpxlvk7tmlvtjsixdtrnseven3d\n" +
                        "5jlb4\n" +
                        "jhkslf976fpseven\n" +
                        "jpfive1\n" +
                        "two2jpfztkeightssfsevennine56\n" +
                        "seven6rjchpgvmqgrxdddq\n" +
                        "four7eight\n" +
                        "zqoneight9mqmjtjcb\n" +
                        "ljcmvjf1ngrgzmttttqprks2kphjtgqvmeightvfmzqhdhgj\n" +
                        "77ninejjxxgbffive6zzgd\n" +
                        "4pthree5zp3one\n" +
                        "mhdzcmmsseven4three3bngxxqzclpkmcppxtwo\n" +
                        "bneightwo33ptmpcbfournine4five\n" +
                        "sevenfrzffbklg4dmdngxmsixnzjgpkngsfivetwo6\n" +
                        "six2onethreethree\n" +
                        "xhx4gvkbtcjbqvrhtwo6\n" +
                        "1mdfvninevchtrqthree\n" +
                        "onecrnninedjchhzkmzthree4qjnclshjlbn\n" +
                        "threeccgbz6sixlhnkcpfdzk119\n" +
                        "61dtwo\n" +
                        "ncsbdxnp43jlrxfhgzlrfzqjkzbkd\n" +
                        "nxfztwo9lhcc\n" +
                        "mds9vkninehzcdk\n" +
                        "twofive4jdcndg\n" +
                        "374\n" +
                        "threedrsh9eightcqkrslljl5tthree\n" +
                        "fourtwotwo8kl1bvplqfrc7\n" +
                        "threekldmmjkmc92sixsixonenine6\n" +
                        "bllccpcksq59zznr\n" +
                        "n35lxtnq3\n" +
                        "25hmzzxv\n" +
                        "38sevenkqgtfcpnj\n" +
                        "ntfceightmvhvnzjvv37bsj\n" +
                        "4sixfvrtgdsjvxsevenfouronefiveddns2\n" +
                        "eight29lnznht2oneonekgjkq\n" +
                        "4lthkrtj1onesevenninerfplsixfhxdvlhoneighth\n" +
                        "1seven8eightgxzvgmnqj\n" +
                        "7qfqvxcjttwoeighteightqqsgbsftseight\n" +
                        "slfqkljnine1oneeightlgskmlqgstwo\n" +
                        "sppqhlxqzkdtdqc6qtxsssdcf41\n" +
                        "tnggpjrnmrrgzpssptpk32\n" +
                        "6pcjglgdknjoneightssb\n" +
                        "ninefivefrglbccjmrchvbpsgxrq15fourfive\n" +
                        "7five1lmndzphnj4fouronesj\n" +
                        "jvhkb24htseven7\n" +
                        "7sevensjnrvxmsixthreesevengrh\n" +
                        "9h5xbdgpdjjkt1\n" +
                        "c14vbjvcv\n" +
                        "ninetwohfbm6fourjpgz676\n" +
                        "gqdtlzqvkplj48cxvtvjjlkmbstcfxd5hkbfdgtf\n" +
                        "ninelpxd8eightvmmbvgmhs3six1\n" +
                        "9mmlj4vvcxlnbsfoureight\n" +
                        "nzrjlxqhnffour1\n" +
                        "hl5fzsxdbvklx4five\n" +
                        "182ninedghflcgrqz4ns\n" +
                        "eightdmbqddsqmfive7qshcvdjx\n" +
                        "vdfzsevenoneone4ninemhclrkjspkxt\n" +
                        "2three1qzqhscbvmpnine86three\n" +
                        "1ninevvlzft\n" +
                        "1ghfnrvkn97sixqzgtm32\n" +
                        "sixnine4rsjghcsznfvs\n" +
                        "ph5mzknlknp5\n" +
                        "3eight3twotchnsqdtbkh\n" +
                        "63threerjlgv6three\n" +
                        "fivevvcmvrqfkdfshxjnfgsevensix3seven8\n" +
                        "21onebcsgvhtm6two\n" +
                        "bnjpqcqdzmeight2gtjhqeight\n" +
                        "1rsjbbhtkbbfourqzdhlone4eighttwo\n" +
                        "6jpnnlbstgjfjdrdgnthreepgh49hdxqghr\n" +
                        "five3oneonefrvnbnnlz\n" +
                        "gbseven9five6\n" +
                        "nine2hdltdjdp73phzrjnonegx\n" +
                        "3two3eightjszbfourkxbh5twonepr\n" +
                        "5cfprzgxtf3465five"
        ));
    }
}